# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91e5b16b7cd108d03ec4af436176ffd182777ca0515040e61f0ef3f58dd8e81a87772c5b9f12c3dc5f95e3d5180df95cd0f58fbad72c1df9e326432aec3540f0

test:
  secret_key_base: ea15c20881057edbc5eb3d7a93cd669ed9cd7729e34a095279c56691b0fb3a8265dd2c5be66737863b5b1fc54e00ed75375f84dc468dea2ec5774ca9852ee4fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
